title: My Marbles
description: Play online with others, and win all the marbles
google_analytics: [Your Google Analytics tracking ID]
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
